### ISSUE TITLE
hello，can you have plan to achieve  the NMAR?

### ISSUE THREAD

**Issue by hyaihjq** [LLNL/LEAP#104]

**Comment by kylechampley** [comment]
I have no plans to add NMAR.  NMAR is a popular MAR technique, but I don't know why because it is actually very unstable.

In LEAP, we have a much better MAR algorithm; the reference is [here](https://www.osti.gov/servlets/purl/1557944).

And a demo script using it is [here](https://github.com/LLNL/LEAP/blob/main/demo_leapctype/d30_MAR_and_sinogram_replacement.py).

**Comment by hyaihjq** [comment]
Thanks

**Comment by argman** [comment]
> I have no plans to add NMAR. NMAR is a popular MAR technique, but I don't know why because it is actually very unstable.
> 
> In LEAP, we have a much better MAR algorithm; the reference is [here](https://www.osti.gov/servlets/purl/1557944).
> 
> And a demo script using it is [here](https://github.com/LLNL/LEAP/blob/main/demo_leapctype/d30_MAR_and_sinogram_replacement.py).

I implement a nmar method https://github.com/LLNL/LEAP/wiki/Installing-and-Using-LEAP, leap provides really fast fan beam projection and reconstruction compared to astra-toolbox

**Comment by hyaihjq** [comment]
> > I have no plans to add NMAR. NMAR is a popular MAR technique, but I don't know why because it is actually very unstable.
> > In LEAP, we have a much better MAR algorithm; the reference is [here](https://www.osti.gov/servlets/purl/1557944).
> > And a demo script using it is [here](https://github.com/LLNL/LEAP/blob/main/demo_leapctype/d30_MAR_and_sinogram_replacement.py).
> 
> I implement a nmar method https://github.com/argman/NMAR.git, leap provides really fast fan beam projection and reconstruction compared to astra-toolbox

thanks for your share
