### ISSUE TITLE
SART reconstruction

### ISSUE THREAD

**Issue by hy010227** [LLNL/LEAP#111]
When using SART for image reconstruction, some strange stripes or artifacts may appear，like this

![6c1eaccb22634023eb2a9ef3d0c8afc](https://github.com/user-attachments/assets/66f5b9f5-e2ec-42b9-ba74-4b387af420ac)

**Comment by kylechampley** [comment]
Ya, that looks terrible.  Can you share a sample script that recreates the issue or at least send me the CT geometry parameters that you are using?

**Comment by kylechampley** [comment]
Anyway, you can share the data as well?  So far, I cannot reproduce the result.  The root cause of the issue might be a combination of the data and a bug in the SART algorithm.  Other than that, I have a few other comments.

1) I am surprised you are using a non-zero value for tau.  Have you tried using a centerCol value of 454.28 instead?
2) Why use SART for reconstruction?  Your data has a lot of angles, so FBP should produce a good result.
3) Have you tried RWLS?
