### ISSUE TITLE
filter-backprojection and backprojection

### ISSUE THREAD

**Issue by xiti-helloworld** [LLNL/LEAP#123]
Hi Kyle,
I tried to build a demo to explain difference between filter-backprojection and backprojection, but I found that with same sino data input, the output of filter-backprojection(fbp) is far away different compare to backprojection's output. It is not reasonable. Did you compare it before?
Thanks.

**Comment by kylechampley** [comment]
Yes, I have definitely verified the accuracy of the backprojectors in LEAP.  A backprojection and an FBP reconstruction should look quite different.  What were you expecting?

**Comment by xiti-helloworld** [comment]
Thanks, Kyle.

I use d99_speedTest.py under folder demo_leapctype as example. Once FORILD head phantom was set, USLof f is ~0.036, after forward projection, USL of g is ~5.79, then backproject it into image space,  USL of f is ~1069. 1000x increase.  What is the unit of this value in projection domain and image domain?

Maybe I miss understand backprojection, I thought its value may keep same order as it is in image space.

**Comment by kylechampley** [comment]
A backprojection is unitless, while a reconstruction (e.g., FBP) has units of Linear Attenuation Coefficient (LAC) which is basically units in inverse length.

To give you an idea of how arbitrary the number are in a backprojection, say you backproject N projections and you also backproject 2N projections.  Then the result of backprojecting 2N angles will have values that are twice the value of the result from backprojecting N angles.
 
Remember the backprojection operator is just transpose (adjoint) of the forward projection operator, while the FBP operator is the inverse operator of the forward projection operator.

**Comment by xiti-helloworld** [comment]
Thanks for your detail explanation, Kyle.
I can understand backprojection is the transpose of forward projection from math point of view.
In a practical way, build a backprojector from scratch may help to handle it better. Besides learning from your code, can you suggest some paper for start?

**Comment by kylechampley** [comment]
I personally learned from Frank Natterer's books, but I am a mathematician.  I think the best way to learn is by reading PhD thesis of people in the field.  They tend to explain things more thoroughly.  It's been a while since I did this, but from what I remember I liked the PhD thesis from the following people:

[Johan Sunnegardh](https://www.diva-portal.org/smash/get/diva2:232734/FULLTEXT01.pdf)
[Frank Dennerlein](https://citeseerx.ist.psu.edu/[document](https://citeseerx.ist.psu.edu/document?repid=rep1&type=pdf&doi=c594ca0fc6670fbbb57131c7ddbc5b80bbde52b5)?repid=rep1&type=pdf&doi=c594ca0fc6670fbbb57131c7ddbc5b80bbde52b5)

**Comment by kylechampley** [comment]
I'm going to close this issue, but feel free to re-open it if you have any more questions.
