### ISSUE TITLE
Is there any way the FBP algorithm in leap can improve the spatial resolution

### ISSUE THREAD

**Issue by Y7NINE** [LLNL/LEAP#128]
This is a reconstruction of the leap toolkit
![image](https://github.com/user-attachments/assets/da85b873-b883-43ab-9bf3-e2eb5540d135)

This is an image reconstructed by other kits
![image](https://github.com/user-attachments/assets/37d6f262-8954-4360-93c7-3d82f249a6db)

I have tried to modify some parameters in the user manual to improve the spatial resolution, but it is clear that there are better suggestions
![image](https://github.com/user-attachments/assets/12628cbb-4615-412f-9f81-914cb294a047)

![image](https://github.com/user-attachments/assets/29bee3ab-ded7-4e94-8911-61c40168690c)

Here is the python code
---------------------------------------------------------

import numpy as np
from leap_preprocessing_algorithms import *
from leapctype import tomographicModels
leapct = tomographicModels()
import tifffile as tiff

numAngles = 800
numRows = 1024
numCols = 1328
pixelSize = 0.3
xh_offset = 160
centerCol = 0.5*(numCols-1) - xh_offset/pixelSize
sod = 566.13
sdd = 1008.79

# angles = np.linspace(-180, 180, numAngles).astype(np.float32)

na = numAngles
betas_rad = np.zeros(na, dtype=np.float32)

for idx in range(na):
    betas_rad[idx] = -float(idx) / float(na) * 2.0 * np.pi

angles = np.degrees(betas_rad)

leapct.set_conebeam(numAngles, numRows, numCols, pixelSize, pixelSize, 0.5*(numRows-1), centerCol, angles, sod, sdd)
leapct.set_offsetScan(True)
leapct.set_truncatedScan(True)
leapct.set_volume(1024, 1024, 400, 0.371, 0.371, 0, 0, 0)
leapct.set_projector('VD')
#leapct.set_rampFilter(10)
leapct.print_parameters()

g = tiff.imread('E:\LEAP-1.23\LEAP-1.23\proj160.tif')
air = tiff.imread(r'E:\LEAP-1.23\LEAP-1.23\air160.tif')

ROI = [30, 80, 950, 1000]
makeAttenuationRadiographs(leapct, g, air , None, ROI)

vol = leapct.allocateVolume(0)
leapct.FBP(g,vol)
leapct.display(vol)

**Comment by kylechampley** [comment]
Did you resolve this issue?  To me it looks like you specificed the CT geometry parameters incorrectly.

**Comment by Y7NINE** [comment]
@kylechampleyYes, your answers always make me feel fresh and inspired

**Comment by kylechampley** [comment]
So you were able to resolve the CT geometry issues?

Yes, I am aware of how other CT reconstruction library define their ramp filters, but I feel strongly that the ramp filters used in LEAP are much better.  See the Section 13 of the [LEAP technical manual](https://github.com/LLNL/LEAP/blob/main/documentation/LEAP.pdf).

Adding a window function is the same thing as just applying an additional low-pass filter to the data and you can include that step in LEAP using [set_FBPlowpass](https://leapct.readthedocs.io/en/latest/fbp.html#leapctype.tomographicModels.set_FBPlowpass).

**Comment by Zhentao-Liu** [comment]
@kylechampley When I set set_FBPlowpass(w=2) it looks blurrier than w=1 (default). I think maybe provide a selection of filter (e.g., 'hann') for user to choose would be better. As I wonder if 'hann' would give better results than ram-lak.

**Comment by kylechampley** [comment]
There are two methods that change the ramp filter in LEAP.
1) leapct.set_rampFilter(n)
2) leapct.set_FBPlowpass(w)

The first method can be used to create sharper and sharper ramp filters, while the second method can be used to blur the ramp filter defined in the first method by a low pass filter.  Read the documentation on these to see how they work.  There is also a very detailed explanation of the ramp filters used in LEAP in the [technical manual](https://github.com/LLNL/LEAP/blob/main/documentation/LEAP.pdf).
 
I'm not sure who started this Han filter business in FBP reconstruction, but it is such a terrible idea.  These filters are based on applying a window function to the Ram-Lak filter, but the Ram-Lak filter is a terrible place to start because this filter creates lots of ringing artifacts.
