### ISSUE TITLE
Jitter correction makes some warning message relating to rebin

### ISSUE THREAD

**Issue by hws203** [LLNL/LEAP#132]
@kylechampley I added some jitter correction algorithm with leapct, and I can see some warning message from leapct as like below. I wonder it does not bring any side effect into all reconstruction action. If I use uneven angle space then it is normal of this warning message?

![rebin_warn](https://github.com/user-attachments/assets/a3bfcbcd-17bb-4e02-9e04-9d9d9b4632ea)

**Comment by hws203** [comment]
Below is my jitter correction algorithm flow.

1. estimate angle deviation from 0 to 360 each degree projection images with phase correlation. 
2. update angle table with this deviation into leapct class's angle table memory.
3. FDK call for full reconstruction.
4. below is my result between corrected and not-corrected.

![jitter](https://github.com/user-attachments/assets/05e06b83-ea37-49df-9643-0770fb7c8356)

**Comment by kylechampley** [comment]
You must be using either rebin_parallel or estimate_tilt right?  I hope you are not rebinning to cone-parallel coordinate because I would only recommend this if you are doing medical CT.  Anyway, this is just a warning, not an error.  The code that does the interpolation uses Lagrange polynomial interpolation.  I think the default is to use a 6th order polynomial.  But if your projection angles are non-equi-spaced, I just use linear interpolation.  I did this because it was too much of a pain to figure out how to do this efficiently with higher order polynomials.  The overall impact is that linear interpolation gives a result that is not as sharp.

**Comment by hws203** [comment]
Current just warning is not critical for my application. I will keep it. Thanks so much for explanation.
