### ISSUE TITLE
Detector  rotation functions for three cases(skew, tilt, rolling)

### ISSUE THREAD

**Issue by hws203** [LLNL/LEAP#41]
@kylechampley  I checked your detector rotation function . And I am wondering why this function  combined with two more factors, for example, tilt+skew, or skew+roll.

Detector is fixed into a equipment mechanically at most case. But there are sometime some mismatching angles of three factors. So from the real projection image, we need to extract these error angles for exact reconstruction. For this case, we may needs three separated functions for geometry correction.

I think that at least there needs to exist of three separated functions for tilt-rotate(), skew-rotate() and roll-rotate() of detector.
How about your opinion ? 

![skew_tilt_rolling](https://github.com/LLNL/LEAP/assets/73321363/ebff4f49-315b-4416-b75f-820a7f9e9c2a)
![detector_rot_0_180](https://github.com/LLNL/LEAP/assets/73321363/bb589191-1f16-470a-9330-8dba0aee8e89)
![detector_rot_90](https://github.com/LLNL/LEAP/assets/73321363/d1d3f79c-3b9a-4054-a564-6138850e3808)

**Comment by kylechampley** [comment]
Yes, as you've pointed out LEAP only has a function to perform what you've labeled as a "skew" rotation.  In LEAP we sometimes call this detector tilt (which conflicts with what you have above) and the function is leapct.rotate_detector(rotationAngleInDegrees).  If you want to perform the other rotations, you have to manually manipulate the geometry specification yourself.

We have not included a function for this yet largely for three reasons:
1) there are many definitions of how to perform 3D rotations: Euler angles (extrinsic or intrinsic), quaternions, etc.  Some people might think it doesn't work because they are using different rotation conventions.
2) Using your notation, one has to perform large angle "roll" and "tilt" rotations to make a significant effect on image quality.  Try a reconstruction where you are off by a couple of degrees of these types of rotations and you'll see only very slight changes in the reconstruction.  On the other hand, the reconstruction is heavily effected by "skew" rotations.
3) Lastly, note that one can model "roll" rotations by the "tau" parameter in LEAP.

**Comment by kylechampley** [comment]
I changed my mind.  I'll add it to the next release.  Just check the online documentation for usage.

**Comment by kylechampley** [comment]
A new version of LEAP has been posted that will perform these rotations.  See description here: 
https://leapct.readthedocs.io/en/latest/ctgeometries.html#leapctype.tomographicModels.rotate_detector

**Comment by hws203** [comment]
I have checked your detection rotation function which looks good.  By the way, I have researched some papers about self calibration of fan-bean or cone beam ct.  And I think that the paper sent to your e-mail just now may need to be checked for  your Leap's new feature of self-online calibration which could be useful for not correct geometry system in real.

**Comment by hws203** [comment]
At the case of 3x3 matrix input of alpha, not scalar. I can see some error message in python command as like pictures.
![matrix_error01](https://github.com/LLNL/LEAP/assets/73321363/8b0f9a57-a9c0-4996-b7e8-fe9eb280bb3c)
![matrix_error01_script](https://github.com/LLNL/LEAP/assets/73321363/b9ce2dc5-05ff-40f8-94fc-ae2c6770d886)

**Comment by hws203** [comment]
Above issue is related to my python environment. After "pip install ." command , all looks good. it is not related to your own library function.

**Comment by hws203** [comment]
Now  I can see almost exact reconed slice of my sample owing to your new detector rotate function.
Thanks for your updating.
![exact_slice](https://github.com/LLNL/LEAP/assets/73321363/8be773ff-190c-4f66-9591-f7685d3b02b3)

**Comment by ProjX0** [comment]
@hws203 The above results are very interesting. Could I possibly see the entire code used to produce them?

**Comment by hws203** [comment]
My code has no special ones to make the above result, I do several manual retrials to make it.  I hope that the next release LEAP could include such auto calibration feature that you want too.

**Comment by kylechampley** [comment]
@hws203 and @ProjX0, I am working on an automatic calibration algorithm that should be ready by the end of the week.  I'll let you know when it's ready.

**Comment by kylechampley** [comment]
I just released [v1.13](https://github.com/LLNL/LEAP/releases/tag/v1.13) which has several bug fixes related to modular-beam with rotated detector and I added some utilities to help with geometric calibration.

See [d12_geometric_calibration.py](https://github.com/LLNL/LEAP/blob/main/demo_leapctype/d12_geometric_calibration.py)

**Comment by hws203** [comment]
Yes, I have checked your new auto-cal of consistency-cost which looks  nice.  I can see the correct my sample slice without any labor work now.  I will check it with my cylinder batter image too, Today. I really appreciate your new function for auto-cal.

![full_ato_cal](https://github.com/LLNL/LEAP/assets/73321363/a6248d6f-dea2-43c4-b746-0cfeae6b034a)

**Comment by kylechampley** [comment]
I'm going to close this issue because it seems like things have been resolved.  If you find another bug, please open a new issue, but if you just want to start a conversation about a topic, please open a new discussion thread instead.
