### ISSUE TITLE
any advice on projection angle correction

### ISSUE THREAD

**Issue by lc82111** [LLNL/LEAP#53]
Thank you for the recent update on geometric correction, which has been extremely useful for solving real-world problems. In my CBCT system, I am facing an issue with an unreliable angle sensor, so I am forced to estimate the angles from 0 to 360 degrees, which unfortunately degrades the quality of the reconstructions. I have tried to maximize the gradient/sharpness of volume, but such loss may maximize the noise. I believe that adjusting the 'sweep_parameter' and 'consistency_cost' might help address this issue. I would appreciate any advice you can offer on this matter. Thank you once again.

**Comment by kylechampley** [comment]
Hello.  Although LEAP can handle arbitrary projection angles, it does not have any geometric calibration routines to handle finding unknown projection angles.  In addition, I am not aware of any algorithm to solve this problem.  Since geometric calibration has been a popular topic in the LEAP discussions over the past several weeks, I started a discussion on this topic.  You can find it [here](https://github.com/LLNL/LEAP/discussions/54).

**Comment by lc82111** [comment]
thanks for the response. I will close this issue.
