### ISSUE TITLE
GPU memory chunking error

### ISSUE THREAD

**Issue by hws203** [LLNL/LEAP#59]
@kylechampley   I can see that your current chucking method has some issue, when I use 720x2196x2404(numAngle,numRows, numCols) projection images, there is exceptional error which comes from the last chuck is overflow.

So I changed the maxSlicesForChunking to 180 from 128, because it is closely related to numAngle value. As you know, 720/128 = 5.625, which is not integer, so there should be residual memory area.

My modification is temporal, please adapt your final modification at your next release.

**Comment by kylechampley** [comment]
I'm sorry I don't understand your post.  What is the issue?  The chunk sizes don't have to divide evenly; the last chunk can be a different size.

**Comment by hws203** [comment]
Yes it is. the last chunk size is over the size of real projection mem-size, so there is exceptional error happens.  I guess that the difference comes from the one between the host-alloc-size and gpu-alloc-size.

**Comment by kylechampley** [comment]
Oh, I see this is with the 2D median filter.  You should have stated that in your original post.  This is an easy fix, all you have to do is replace:
medianFilter2D(f_chunk, numSlices, N_2, N_3, threshold, w, true, whichGPU);
with this:
medianFilter2D(f_chunk, sliceEnd - sliceStart+1, N_2, N_3, threshold, w, true, whichGPU);

This be fixed in the next LEAP release.

**Comment by hws203** [comment]
Yes, that modification works well.
