### ISSUE TITLE
Can we intinialize the CT image when do iterative reconstruction methods on sinogram?

### ISSUE THREAD

**Issue by GreameLee** [LLNL/LEAP#68]
When I try to add this process in diffusion model. I need insert LEAP with another reconstruction methods. So I need the iterative reconstruction method such as SART can take the processed CT images as the initial image to use its corresponding sinogram reconstruct images. So can I initialize the image?

**Comment by kylechampley** [comment]
Yes, you definitely can do this with LEAP.  In LEAP, when you run any iterative reconstruction algorithm the first argument is the CT projection data (sinogram) and the second argument is the CT volume data.  This volume data can have values from a different reconstruction method or it can be all zeros for a fresh start- whatever you want.  There are several demo scripts that demonstrate this being done, one for example is this one: [d29_filter_sequence.py](https://github.com/LLNL/LEAP/blob/main/demo_leapctype/d29_filter_sequence.py).

I assume that since you are asking this question that you were able to install LEAP.  Would you mind letting me know how you resolved your issue?

**Comment by GreameLee** [comment]
Yes, I have replied to that issue. And there is another question about the CT reconstruction algorithm. I see there is an iterative algorithm called OS-SART in the readme file but I can not find it in code. Is this method available to the public now?

**Comment by kylechampley** [comment]
In the code it is just called SART.

**Comment by kylechampley** [comment]
Were you able to run the SART algorithm successfully?  Just wondering if I should keep this issue open.

**Comment by GreameLee** [comment]
Yes, I have solved it. Thanks for your help
